package com.qa.domain;

public enum Genre {
	ACTION, ADVENTURE, ANIMATION, BIOGRAPHY, COMEDY, 
	CRIME, DOCUMENTARY, DRAMA, FAMILY, FANTASY, 
	FILM_NOIR, HISTORY, HORROR, MUSIC, MUSICAL, 
	MYSTERY, ROMANCE, SCI_FI, SHORT, SPORT, 
	SUPERHERO, THRILLER, WAR, WESTERN;
}
